version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: billun_db
      POSTGRES_USER: billun_user
      POSTGRES_PASSWORD: billun_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://billun_user:billun_pass@db:5432/billun_db
      SMTP_SERVER: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: ton.email@gmail.com
      SMTP_PASSWORD: ton_mdp_app
      SECRET_KEY: "change_this_secret_key"
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    restart: unless-stopped

volumes:
  postgres_data: 